fossbarcode/urls.py
from django.conf.urls.defaults import *
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'^barcode/$', 'fossbarcode.barcode.views.input'),
    (r'^barcode/checksum/(?P<checksum>[0-9a-fA-F]+)$', 'fossbarcode.barcode.views.by_checksum'),
    (r'^barcode/input/$', 'fossbarcode.barcode.views.input'),
    (r'^barcode/documentation/$', 'fossbarcode.barcode.views.documentation'),
    (r'^barcode/records/$', 'fossbarcode.barcode.views.records'),
    (r'^barcode/search/$', 'fossbarcode.barcode.views.search'),
    (r'^barcode/search_dupes/$', 'fossbarcode.barcode.views.search_dupes'),
    (r'^barcode/queued_upload/$', 'fossbarcode.barcode.views.queued_upload'),
    (r'^barcode/sysconfig/$', 'fossbarcode.barcode.views.sysconfig'),
    (r'^barcode/taskstatus/$', 'fossbarcode.barcode.views.taskstatus'),
    url(r'^barcode/(?P<record_id>\d+)/detail/$', 'fossbarcode.barcode.views.detail', name="detail-url"),
    url(r'^barcode/(?P<record_id>\d+)/detail/(?P<revision>[0-9a-fA-F]+)$', 'fossbarcode.barcode.views.detail', name="detail-revision-url"),
    url(r'^barcode/(?P<record_id>\d+)/detail/(?P<revision>[0-9a-fA-F]+)/(?P<path>.+)$', 'fossbarcode.barcode.views.history_file', name="history-file-url"),
    url(r'^barcode/(?P<record_id>\d+)/json/history/$', 'fossbarcode.barcode.views.history_json', name="history-url"),
    url(r'^barcode/licenses/$', 'fossbarcode.barcode.views.licenses_json', name='licenses-url'),
    url(r'^barcode/licenses/new$', 'fossbarcode.barcode.views.new_license', name='new-license-url'),
    url(r'^barcode/licenses/(?P<license_id>\d+)/json/$', 'fossbarcode.barcode.views.license_json', name='license-url'),
    (r'^site_media/js/history.js', 'fossbarcode.barcode.views.history_js'),
    (r'^site_media/(?P<path>.*)$', 'django.views.static.serve',
	            {'document_root':  settings.STATIC_DOC_ROOT}),
    (r'^admin/', include(admin.site.urls)),
)

fossbarcode/barcode/models.py
from django.conf import settings
from django.db import models
from django.forms import ModelForm, forms, Form
from django import forms
import os
import re
import shutil
import pickle
import time
import hashlib
import subprocess
from dulwich.repo import Repo
from dulwich.objects import parse_timezone

# Custom exceptions.
class FileDataMixinCreateError(StandardError):
    pass

class ReadOnlyError(StandardError):
    pass

# Utility functions.

# strip 'pk' entry from serialized data
def strip_pk(data):
    data = re.sub('pk=".*?" ','', data)
    return data

# This is a special mix-in class which implements the loading and
# saving of some attributes via a pickle file.  It allows us to use
# traditional version control to audit certain data changes.
class FileDataMixin:
    # To use a FileDataMixin class, define this to be an array
    # of attribute names.  This will be called to get the ID
    # of the FileDataDirMixin object which should control the files.
    # For example, if the FileDataDirMixin object is accessed via
    # self.foo.bar, set this to ["foo", "bar"].
    _master_class_path = None

    # This should be set to a dict.  Each key becomes an attribute
    # of the class, and each value a tuple containing the data type
    # or class for this attribute and its default value.  So, for 
    # example, to have a string attribute named "foo" with a blank
    # default, you set this key-value pair:
    #   "foo": (str, "")
    # which then can be accessed via self.foo.
    _file_fields = None

    # These are calculated based on a number of things, including
    # the _master_class_path setting above.
    _master_class = None
    _file_path = None
    _file_name = None

    def set_master_class(self):
        if not self._master_class:
            o = self
            for p in self._master_class_path:
                o = getattr(o, p)
            self._master_class = o

            if not self._master_class.setup_directory():
                raise FileDataMixinCreateError()

    def set_data_path(self):
        if not self._file_path:
            self.set_master_class()
            self._file_path = self._master_class.file_path()

    def set_data_fn(self):
        if not self._file_name:
            fn_base = self.__class__.__name__ + "_%d.pickle"
            filenum = 1
            fn = fn_base % filenum
            while os.path.exists(os.path.join(self._file_path, fn)):
                filenum = filenum + 1
                fn = fn_base % filenum
            self._file_name = fn

    def sanitize_init(self, kwargs):
        new_kwargs = kwargs.copy()
        for key in kwargs:
            if key in self._file_fields:
                self.__dict__[key] = new_kwargs[key]
                del new_kwargs[key]
        return new_kwargs

    def load_from_fn(self, revision=None):
        self.set_data_path()
        self.set_data_fn()

        # Set defaults.
        for field in self._file_fields:
            if field not in self.__dict__:
                self.__dict__[field] = self._file_fields[field][1]


        try:
            record_data = self.brecord.get_file_content(self._file_name,
                                                        revision)
            if record_data:
                read_from = pickle.loads(record_data)
                self.__dict__.update(read_from)
        except KeyError:
            pass

    def write_to_fn(self):
        self.set_master_class()
        self.set_data_path()
        self.set_data_fn()

        to_write = {}
        for key in self.__dict__:
            if key in self._file_fields:
                to_write[key] = self.__dict__[key]

        path = os.path.join(self._file_path, self._file_name)
        file_exists = os.path.exists(path)
        f = open(path, "w")
        pickle.dump(to_write, f)
        f.close()
        if file_exists:
            self._master_class.register_modified_file(self._file_name)
        else:
            self._master_class.register_new_file(self._file_name)

# This mixin class actually manages the files being created by the
# FileDataMixin class.  Whichever model ends up being the "master"
# model should derive from this.  It handles the details of setting up
# the directory and the version control repository, and also handled
# commits and history.
class FileDataDirMixin:
    _subdirs = None
    current_changes = []

    def file_path(self):
        return os.path.join(settings.USERDATA_ROOT, str(self.id))

    def get_repo(self):
        return Repo(self.file_path())

    def setup_directory(self):
        file_path = self.file_path()
        if not os.path.isdir(file_path):
            try:
                os.makedirs(file_path)
                if self._subdirs:
                    for subdir in self._subdirs:
                        os.mkdir(os.path.join(file_path, subdir))
            except OSError:
                if os.path.exists(file_path):
                    shutil.rmtree(file_path)
                return False

            repo = Repo.init(file_path)

        return True

    def remove_directory(self):
        shutil.rmtree(self.file_path())

    def _add_blob_from_file(self, subpath):
        self.current_changes.append(subpath)

    def new_file_from_existing(self, orig_path, subdir=None):
        if subdir:
            dest_path = os.path.join(self.file_path(), subdir)
            dest_subpath = os.path.join(subdir, os.path.basename(orig_path))
        else:
            dest_path = self.file_path()
            dest_subpath = os.path.basename(orig_path)
        shutil.copy(orig_path, dest_path)

        self._add_blob_from_file(dest_subpath)

    def new_file_from_submit(self, file_data, subdir=None):
        if subdir:
            dest_path = os.path.join(self.file_path(), subdir)
            dest_subpath = os.path.join(subdir, file_data.name)
        else:
            dest_path = self.file_path()
            dest_subpath = file_data.name
        dest = open(os.path.join(dest_path, file_data.name), 'wb+')
        for chunk in file_data.chunks():
            dest.write(chunk)
        dest.close()
 
        self._add_blob_from_file(dest_subpath)

    def register_new_file(self, subpath):
        self._add_blob_from_file(subpath)

    def register_modified_file(self, subpath):
        self._add_blob_from_file(subpath)

    def delete_file(self, subpath):
        os.unlink(os.path.join(self.file_path(), subpath))
        self.current_changes.append(subpath)

    def iter_history(self):
        repo = self.get_repo()
        for commit in repo.revision_history(repo.head()):
            yield (commit.id, commit.commit_time, commit.message)

    def get_file_content(self, subpath, revision=None):
        if revision:
            repo = self.get_repo()

            traverse = repo.commit(revision).tree
            for path_component in os.path.split(subpath):
                if path_component:
                    traverse = repo.tree(traverse)[path_component][1]
            return repo.get_blob(traverse).data
        else:
            data_full_path = os.path.join(self.file_path(), subpath)
            if os.path.exists(data_full_path):
                data_file = open(data_full_path)
                return data_file.read()
            else:
                return ""

    def commit(self, commit_msg):
        if not self.current_changes:
            return False

        # FIXME: get real values for these.
        author = "FOSS Barcode <foss-barcode@linuxfoundation.org>"
        tz = parse_timezone('-0400')[0]

        repo = self.get_repo()
        repo.stage([str(x) for x in self.current_changes])
        commit_id = repo.do_commit(commit_msg, committer=author,
                                   commit_timezone=tz)

        self.current_changes = []
        return True

class Product_Record(models.Model, FileDataDirMixin):
    class Meta:
        verbose_name = "product record"

    _subdirs = ["spdx_files", "patches", "copyrights", "attributions"]

    company = models.CharField('Company Name', max_length=200)
    product = models.CharField('Product Name', max_length=200)
    version = models.CharField('Product Version', max_length=20)
    release = models.CharField('Product Release', max_length=20)
    checksum = models.CharField('Checksum', max_length=200, blank=True)
    website = models.CharField('Company Website', max_length=200)
    record_date = models.DateTimeField('Last Updated', auto_now=True)
    contact = models.CharField('Compliance Contact Name', max_length=200, blank=True)
    email = models.EmailField('Compliance Contact Email', max_length=200)
    spdx_file = models.CharField('SPDX<sup>TM</sup> File', max_length=200, blank=True)
    release_date = models.DateField('Release Date', null=True)

    def __unicode__(self):
        return self.product

    def delete(self, *args, **kwargs):
        product_path = self.file_path()
        super(Product_Record, self).delete(*args, **kwargs)
        shutil.rmtree(product_path)

    def clone(self, company=None, product=None, version=None, release=None, website=None, contact=None, email=None, spdx_file=None):
        # Create a clone of this product, including the same components,
        # patches, etc.  Must provide at least one different value for
        # company, product, version, or release.  Returns the new product.
        if not company:
            company = self.company
        if not product:
            product = self.product
        if not version:
            version = self.version
        if not release:
            release = self.release
        if not website:
            website = self.website
        if not contact:
            contact = self.contact
        if not email:
            email = self.email
        if not spdx_file:
            spdx_file = self.spdx_file

        if company == self.company and product == self.product and \
                version == self.version and release == self.release:

fossbarcode/templates/barcode/banner.html
<!-- a href="http://www.linuxfoundation.org/" target="_blank"-->
{% if not public_facing %}
<img hspace="15" vspace="5" align="right" src="/site_media/images/lflogo.png" alt="FOSS Barcode Tool" title="FOSS Barcode Tool" />
{% else %}
<img hspace="15" vspace="5" align="right" src="/site_media/images/{{ public_logo }}" />
{% endif %}

fossbarcode/templates/barcode/base.html
{% include "barcode/header.html" %}

  <!-- sets up the divs to control the styling of the main page body -->
  <style type="text/css">@import "/site_media/css/bodystyle.css";</style>

  <!-- sets up the styles for the progress bar -->
  <style type="text/css">@import "/site_media/css/barstyle.css";</style>

{% block header %} {% endblock %}

<body onload="setdefaults();">

<div id="header">
  {% include "barcode/banner.html" %}
  <ul>
    {% if not public_facing %}
    <li {% if tab_input %}id="current"{% endif %}><a href="/barcode/input">Create<br>Compliance Record</a></li>
    {% endif %}
    <li {% if tab_records %}id="current"{% endif %}><a href="/barcode/records">Review<br>Compliance Records</a></li>
    <li {% if tab_search %}id="current"{% endif %}><a href="/barcode/search">Search<br>Compliance Records</a></li>
    {% if not public_facing %}
    <li {% if tab_sysconfig %}id="current"{% endif %}><a href="/barcode/sysconfig">System<br>Configuration</a></li>
    <li><a href="/barcode/documentation">Tool<br>Documentation</a></li>
    {% endif %}
  </ul>
</div>

<div id="lmargin">&nbsp;</div>
<div id="main">
{% block content %} {% endblock %}
</div> <!-- end of main -->
<div id="rmargin"></div>

</body>

{% block scripts %}
<script type="text/javascript">

function setdefaults()
{
}

</script>
{% endblock %}

fossbarcode/templates/barcode/documentation.html
{% include "barcode/header.html" %}
  <!-- sets up the divs to control the styling of the main page body -->
  <style type="text/css">@import "/site_media/css/docstyle.css";</style>
</head>

<body>

<div id="header">
  {% include "barcode/banner.html" %}
  <ul>
    <li><a href="/barcode/input">Create<br>Compliance Record</a></li>
    <li><a href="/barcode/records">Review<br>Compliance Records</a></li>
    <li><a href="/barcode/search">Search<br>Compliance Records</a></li>
    <li><a href="/barcode/sysconfig">System<br>Configuration</a></li>
    <li id="current"><a href="/barcode/documentation">Tool<br>Documentation</a></li>
  </ul>
</div>

<div>
  <center>
    <b>{{ name }} version {{ version }}.</b>
  </center>
</div>

{% autoescape off %}
{{ gui_docs }}
{% endautoescape %}

fossbarcode/templates/barcode/edit_header.html
<!-- we don't extend base for this one as we don't want the overall tabs/styling -->
{% block content %}
<div id="header-modal-content">
  <!-- form needs to be inside the div -->
  <form name="headerform" id="headerform" method="post" action="" enctype="multipart/form-data">
    <div class="titlem"><span id="header_title"></span></div>
    <!-- usual "container" stype wasn't working here, use containerm -->
    <div class="containerm" id="modal_entry_form">
    <span class="red" id="header_warning"></span>
    <table>
      <tr>
        <td><span class="red"><b>{{ headerform.required_flag }}{{ headerform.company.label }}:</b></span></td>
        <td></td>
        <td><input type="input" id="id_company" name="company" value="{{ record.company }}"></td>
      </tr>
      <tr>
        <td colspan="3">{{ headerform.company.errors }}</td>
      </tr>
      <tr>
        <td><b>{{ headerform.required_flag }}{{ headerform.website.label }}:</b></td>
        <td></td>
        <td><input type="input" id="id_website" name="website" value="{{ record.website }}"></td>
      </tr>
      <tr>
        <td colspan="3">{{ headerform.website.errors }}</td>
      </tr>
      <tr>
        <td><span class="red"><b>{{ headerform.required_flag }}{{ headerform.product.label }}:</b></span></td>
        <td></td>
        <td><input type="input" id="id_product" name="product" value="{{ record.product }}"></td>
      </tr>
      <tr>
        <td colspan="3">{{ headerform.product.errors }}</td>
      </tr>
      <tr>
        <td><span class="red"><b>{{ headerform.required_flag }}{{ headerform.version.label }}:</b></span></td>
        <td></td>
        <td><input type="input" id="id_version" name="version" value="{{ record.version }}"></td>
      </tr>
      <tr>
        <td colspan="3">{{ headerform.version.errors }}</td>
      </tr>
      <tr>
        <td><span class="red"><b>{{ headerform.required_flag }}{{ headerform.release.label }}:</b></span></td>
        <td></td>
        <td><input type="input" id="id_release" name="release" value="{{ record.release }}"></td>
      </tr>
      <tr>
        <td colspan="3">{{ headerform.release.errors }}</td>
      </tr>
      <tr>
        <td><b>{{ headerform.optional_flag }}{{ headerform.contact.label }}:</b></td>
        <td></td>
        <td><input type="input" id="id_contact" name="contact" value="{{ record.contact }}"></td>
      </tr>
      <tr>
        <td><b>{{ headerform.required_flag }}{{ headerform.email.label }}:</b></td>
        <td></td>
        <td><input type="input" id="id_email" name="email" value="{{ record.email }}"></td>
      </tr>
      <tr>
        <td colspan="3">{{ headerform.email.errors }}</td>
      </tr>
      <tr>
        <td><b>{{ headerform.optional_flag }}{{ headerform.release_date.label }}:</b></td>
        <td></td>
        <td>{{ headerform.release_date }}</td>
      </tr>
      <tr>
        <td colspan="3">{{ headerform.release_date.errors }}</td>
      </tr>
      <tr>
        <td colspan="3">
          <span class="red" id="spdx_warn_head"><b>Warning:</b> Adding a top-level SPDX file will remove any BoM SPDX files.</span>
        </td>
      </tr>
      <tr>
        <td><b>{{ headerform.optional_flag }}{% autoescape off %}{{ headerform.spdx_file.label }}{% endautoescape %}:</b></td>
        <td colspan="2" valign="center">
          <!-- crafted css to mask the file input field with a text field/button, use the same name/id as the django FileField -->
          <div class="fileinputs">
	        <input type="file" class="file" id="id_spdx_file_input_file" name="spdx_input_file" 
                   onchange="file_input_to_field('id_spdx_file_input_file', 'id_spdx_file', false);"/>
	        <div class="fakefile">
		      <input type="input" id="id_spdx_file" name="spdx_file" value="{{ record.spdx_file }}">
              <!-- this is just for looks, we really activate the invisible one above -->
		      <input type="button" name="spdxfilename" value="Select"/>
	        </div>
            <a href="#" id="clear_foss_spdx"><img src="/site_media/images/edit-delete.png" width="16" height="16" 
                        alt="edit-delete.png" title="Clear SPDX" 
                        onClick="clear_field('id_spdx_file');clear_value_by_id('id_spdx_file_input_file');"></a>
          </div>
        </td>
      </tr>
      <tr>
        <td colspan="2"><b>{{ headerform.required_flag }}{% autoescape off %}{{ headerform.header_commit_message.label }}{% endautoescape %}:</b></td>
      </tr>
    </table>
    </div>
    <div>
        {{ headerform.header_commit_message.errors }}
    </div>
    <div class="commit_table">
        <table width="100%">
          <tr>
            <td>{{ headerform.header_commit_message }}</td>
          </tr>
          <tr>
            <td align="center"><input type="submit" name="submit" id="submit_header" value="" onclick="return submit_header_validate();"></td>
          </tr>
        </table>
    </div>     
  </form>
</div>
{% endblock %}
{% block scripts %}
<script language="JavaScript">
    // no manual entry for spdx_files
    $("#id_spdx_file")[0].setAttribute("readonly", "true");
    // in the input form we have to play games with top-level spdx vs line-item, here the backend handles the change
    $("#id_spdx_file")[0].setAttribute("onchange", "");

    // set client-side validation rules
    $("#id_website")[0].setAttribute("class", "required url");
    $("#id_email")[0].setAttribute("class", "required email");

    $(document).ready(function(){
        $("#headerform").validate();
    });
</script>
{% endblock %}

fossbarcode/templates/barcode/edit_line.html
<!-- we don't extend base for this one as we don't want the overall tabs/styling -->
{% block content %}
<div id="line-item-modal-content">
  <!-- form needs to be inside the div -->
  <form id="itemform" method="post" action="" enctype="multipart/form-data">
    <div class="titlem"><span id="item_edit_mode">Edit</span> Line Item, id# <span id="line_item_no">N</span>:</div>
    <!-- usual "container" stype wasn't working here, use containerm -->
    <div class="containerm" id="modal_entry_form">
     <table width="100%">
      <tr>
        <td colspan="4">{% autoescape off %}{{ component_select }}{% endautoescape %}</td>
      </tr>
      <tr>
        <td><b>{{ itemform.required_flag }}{{ itemform.foss_component.label }}:</b></td>
        <td>{{ itemform.foss_component }}</td>
        <td colspan="2"></td>
      </tr>
      <tr>
        <td colspan="4">{{ itemform.foss_component.errors }}</td>
      </tr>
      <tr>
        <td><b>{{ itemform.required_flag }}{{ itemform.foss_version.label }}:</b></td>
        <td>{{ itemform.foss_version }}</td>
        <td colspan="2"></td>
      </tr>
      <tr>
        <td colspan="4">{{ itemform.foss_version.errors }}</td>
      </tr>
      <tr>
        <td colspan><b>{{ itemform.required_flag }}{{ itemform.foss_copyright.label }}:</b></td>
        <td>{{ itemform.foss_copyright }}</td>
        <td colspan="2">
          <div class="fileinputs">
	        <input type="file" class="file" id="id_copyright_input_file" name="copyright_input_file" 
                   onchange="file_input_to_field('id_copyright_input_file', 'id_foss_copyright', false);"/>
	        <div class="fakefile">		      
              <!-- this is just for looks, we really activate the invisible one above -->
		      <input type="button" name="copyrightfilename" value="or Select File"/>
	        </div>
          </div>
        </td>
      </tr>
      <tr>
        <td colspan="4">{{ itemform.foss_copyright.errors }}</td>
      </tr>
      <tr>
        <td><b>{{ itemform.required_flag }}{{ itemform.foss_attribution.label }}:</b></td>
        <td>{{ itemform.foss_attribution }}</td>
        <td colspan="2">
          <div class="fileinputs">
	        <input type="file" class="file" id="id_attribution_input_file" name="attribution_input_file" 
                   onchange="file_input_to_field('id_attribution_input_file', 'id_foss_attribution', false);"/>
	        <div class="fakefile">		      
              <!-- this is just for looks, we really activate the invisible one above -->
		      <input type="button" name="attributionfilename" value="or Select File"/>
	        </div>
          </div>
        </td>
      </tr>
      <tr>
        <td colspan="4">{{ itemform.foss_attributions.errors }}</td>
      </tr>
      <tr id="existing_license">
        <td><b>{{ itemform.required_flag }}{{ itemform.foss_license.label }}:</b></td>
        <td>{{ itemform.foss_license }}</td>
        <td colspan="2"></td>
      </tr>
      <tr id="new_license" style="display: none;">
        <form id="new_license_form">
        <td valign="top">      
          <b><label for="new_license_name">New License Name:</label><br />
          <label for="new_license_version">New License Version:</label><br />
          <label for="new_license_url">New License Default URL:</label></b>
        </td>
        <td>
          <input type="text" name="new_license_name" id="new_license_name" /><br />
          <input type="text" name="new_license_version" id="new_license_version" /><br />
          <input type="text" name="new_license_url" id="new_license_url" /><br />
          <input type="button" onclick="new_license()" value="Add New License" />
        </td>
        </form>
        <td colspan="2"></td>
      </tr>     
      <tr>
        <td colspan="4">{{ itemform.foss_license.errors }}</td>
      </tr>
      <tr>
        <td><b>{{ itemform.required_flag }}{{ itemform.foss_license_url.label }}:</b></td>
        <td>{{ itemform.foss_license_url }}</td>
        <td colspan="2"></td>
      </tr>
      <tr>
        <td colspan="4">{{ itemform.foss_license_url.errors }}</td>
      </tr>
      <tr>
        <td><b>{{ itemform.required_flag }}{{ itemform.foss_url.label }}:</b></td>
        <td>{{ itemform.foss_url }}</td>
        <td colspan="2"></td>
      </tr>
      <tr>
        <td colspan="4">{{ itemform.foss_url.errors }}</td>
      </tr>
      <tr>
        <td colspan="4">
          <span class="red" id="spdx_warn_line"><b>Warning:</b> Adding a line-item SPDX file will remove any header SPDX file.</span>
        </td>
      </tr>
      <tr>
        <td><b>{{ itemform.optional_flag }}{% autoescape off %}{{ itemform.foss_spdx.label }}{% endautoescape %}:</b></td>
        <td>{{ itemform.foss_spdx }}</td>
        <td valign="center">  
          <a href="#" id="clear_spdx"><img src="/site_media/images/edit-delete.png"
                      width="16" height="16" alt="edit-delete.png"
                      title="Clear SPDX" onClick="clear_field('id_foss_spdx');clear_value_by_id('id_f_spdx_input_file');"></a>
        </td>
        <td valign="center">
          <div class="fileinputs">
	        <input type="file" class="file" id="id_foss_spdx_input_file" name="foss_spdx_input_file" 
                   onchange="file_input_to_field('id_foss_spdx_input_file', 'id_foss_spdx', false);"/>
	        <div class="fakefile">
              <!-- this is just for looks, we really activate the invisible one above -->
		      <input type="button" name="spdxfilename" value="Select"/>
	        </div>
          </div>
        </td>
      </tr>
      <tr>
        <td valign="top"><b>{{ itemform.optional_flag }}{{ itemform.foss_patches.label }}:</b></td>
        <td rowspan="2">{{ itemform.foss_patches }}</td>
        <td valign="top">
          <a href="#" id="clear_patches"><img src="/site_media/images/edit-delete.png"
                      width="16" height="16" alt="edit-delete.png"
                      title="Clear Patches" 
                      onClick="clear_field('id_foss_patches');clear_extras('id_foss_patches', ['encoded_data', 'data_sizes']);clear_value_by_id('id_patches_input_file');"></a>
        </td>       
        <td valign="top">	
          <div class="fileinputs">
 	        <input type="file" class="file" id="id_patches_input_file" name="patches_input_file" multiple="" 
                   onchange="file_input_to_field('id_patches_input_file', 'id_foss_patches', true);"/>
	        <div class="fakefile">	      
              <!-- this is just for looks, we really activate the invisible one above -->
		      <input type="button" name="patchfilenames" value="Select"/>
	        </div>
          </div>
        </td>
      </tr>
      <tr>
        <td colspan="2">
            <b>{{ itemform.required_flag }}{% autoescape off %}{{ itemform.item_commit_message.label }}{% endautoescape %}:</b>
        </td>
      </tr>
     </table>
    </div>
    <div>
        {{ itemform.item_commit_message.errors }}
    </div>
    <div class="commit_table">
        <table width="100%">
          <tr>
            <td>{{ itemform.item_commit_message }}</td>
          </tr>
          <tr>
            <td align="center">
              <!-- this is where the async file uploads get displayed -->
              <div class="progressor">
                <table id="progress" align="center">
                </table>
              </div>
            </td>
          </tr>
          <tr>
            <td align="center"><input type="submit" name="submit" id="submit_item" value="Update Item" onclick="return submit_line_validate();"></td>
          </tr>
        </table>
        <!-- session_id for queued uploads -->
        <input type="hidden", name="session_id", id="session_id", value="{{ session_id }}">
        <!-- so the back end knows which record to update -->
        <input type="hidden" name="foss_record_id" id="foss_record_id" value="">
        <!-- place to store the encoded patch data -->
        <input type="hidden", name="foss_patch_data", id="foss_patch_data", value="">
    </div>
  </form>
  <!-- store old license ID for license URL management -->
  <div id="old_license_id" style="display: none;">-2</div>
</div> <!-- modal content -->
{% endblock %}
{% block scripts %}
<script language="JavaScript">
    // no manual entry for spdx_files, patches
    document.getElementById('id_foss_spdx').setAttribute('readonly', 'true');
    document.getElementById('id_foss_patches').setAttribute('readonly', 'true');
    // in the input form we have to play games with top-level spdx vs line-item, here the backend handles the change
    document.getElementById("id_foss_spdx").setAttribute("onchange", "");
    // set client-side validation rules
    $("#id_foss_url")[0].setAttribute("class", "required url");
    $(document).ready(function(){
        $("#itemform").validate();
    });
</script>
{% endblock %}

fossbarcode/templates/barcode/header.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <title>FOSS Barcode Tool</title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <style type="text/css">@import "/site_media/css/tabstyle.css";</style>

fossbarcode/templates/barcode/history.html
<!-- we don't extend base for this one as we don't want the overall tabs/styling -->
{% block content %}
<div id="history-modal-content">
  <div class="titlem">Change History, record #<span id="history-modal-content-id"></span>:</div>
  <div class="history">
    <div id="history-modal-content-list">
      <p>Retrieving history...</p>
    </div>
  </div>
</div>
{% endblock %}

fossbarcode/templates/barcode/noscript.html
  <noscript>
    <span class="red">
      <b>This application uses javascript, you should enable it in your browser for full functionality.</b>
    </span>
  </noscript>